deploy_version: 0.1.1
image_tag: latest

applications:
  - name: worker
    image: pennlabs/<image_name>
    secret: example
    extraEnv:
      - name: PORT
        value: 80
    ingress:
      hosts:
        - host: example.com
          paths: ["/"]
